### ISSUE TITLE
Impossibile proseguire il gioco durante il Tutorial

### ISSUE THREAD

**Issue by NarakuITA** [tesivo/VTMB_italian_translation_for_Unofficial_Patch#22]
Vorrei segnalare che non è possibile proseguire, con il tutorial esattamente dopo l'attacco sulla Strada. Il vampiro una volta finito il dialogo non si sposta, rimandano al centro del corridoio e questo impedisce di proseguire...

**Comment by NarakuITA** [comment]
Forse ho capito qual è il problema, Alcuni file, prendiamo ad esempio "line1_col_e.lip" (cartella: Unofficial_Patch\sound\character\dlg\chinatown\ox) nel comando "PHRASE unicode" nella Unofficial_Patch 10.7 è impostato su 98, quello italiano invece è impostato su 134, questo causo un blocco allo script e alcune cose non vengono eseguite, poiché hanno un comando errato. Ad esempio se si gioca con l'inglese il parlato è sempre eseguito correttamente. Tuttavia se si applica la traduzione, molti "audio" dialoghi non vengono eseguiti, forse proprio perché hanno un comando errato. Vedo se posso risolvere io questo problema, così ti levo una rogna in più e ti concentri solo a tradurre il resto mancante. Ed magari ad aggiornare il tutto alla patch 10.9 [https://www.moddb.com/mods/vtmb-unofficial-patch/downloads/unofficial-patch-109](url)

**Comment by tesivo** [comment]
Grazie mille per la segnalazione. Indago sul problema e ti faccio sapere. Intanto dimmi soltanto gli inizi che hai scelto, così che anche io possa incappare nel medesimo bug.

Per quanto riguarda la differenza nel numero che segue UNICODE nei file .lip considera che si riferiscono al numero di caratteri della frase tradotta. Piuttosto, ovunque è ancora presente UNICODE, bisognerebbe sostituire UNICODE con CHAR, perchè crea meno problemi.

A titolo esemplificativo guarda il seguente file: https://github.com/tesivo/VTMB_italian_translation_for_Unofficial_Patch/blob/master/sound/character/dlg/main%20characters/jack_tutorial/line111_col_e.lip
Puoi notare CHAR anziché UNICODE e che lo speaker_name mostra un valore interpretato correttamente.

In ogni caso dimmi che personaggio iniziale hai scelto che verifico di persona il problema.

**Comment by NarakuITA** [comment]
Non sapevo di CHAR. Beh qualcosina potevo fare ma non sono un esperto fino a questo punto XDXDXD Ho visto cmq che molti file sono ancora da tradurre, c'è parecchi da fare. per l'audio ho provato a non copiare la cartella Sound, visto che nessuno dei file è stato tradotto ancora. La traduzione funziona ma l'audio ha lo stesso problema. Dunque non era quello che avevo pensato.
Non saprei proprio perché l'audio del parlato spesso non si sente, quale sia la causa, boh...

Per quanto riguarda l'altro bug, ti passo il salvataggio, poco prima del verificarsi del evento. Così si fa prima (ad ogni modo tutte le scelte erano 1)
[https://drive.google.com/file/d/1fQL808iNd_ikeuJQ33EML0pqcsindewv/view?usp=sharing](url)

**Comment by tesivo** [comment]
Per quanto riguarda le versioni successive alla 10.7: per ora completerei la 10.7, o comunque vedrei di risolvere prima questo problema che hai segnalato, che è grave visto che può impedire di proseguire nel gioco.

Per quanto riguarda il bug(ho provato con il tuo salvataggio e si, jack non si sposta): vedo se sistemando per bene i dialoghi della cartella sound(almeno quell irelativi a jack_tutorial e ox) si sistema o no.

Della cartella sound sono tradotti alcuni dialoghi, ma veramente pochi.

**Comment by tesivo** [comment]
Per ora ho caricato la traduzione di, credo, tutti i dialoghi di Mr. Ox. Devo ancora testarli. Domani completo quelli di Jack_tutorial.

**Comment by NarakuITA** [comment]
Ok, appena domani finisci, la provo anche io. Tienimi aggiornato.

**Comment by tesivo** [comment]
Caricati tutti i dialoghi di Jack nel tutorial. Non ho ancora provato a vedere se risolve il bug

**Comment by NarakuITA** [comment]
Nulla da fare si blocca. Ho provato a rifare tutto da capo, stessa cosa. Inoltre mi sono accorto, ma è un dettaglio piccolo, che all'inizio del filmato della lotta, non appaiono i sottotitoli, delle due misere frasi che il vampiro dice all'inizio del duello.

**Comment by NarakuITA** [comment]
Si, mi riferivo a quei tre dialoghi. Sono una sciocchezza, ma prima comparivano. Spero non sia un problema esteso anche ad altri video durante il gioco, poiché quando finirai di tradurre tutto, immagino anche quelle vengano tradotte e giustamente per capire cosa dicono durante i dialoghi, dovrebbero esserci anche li i sottotitoli. 

Speriamo trivi il problema, sennò tocca usare la spaziatrice, oppure fare una domanda a chi sta continuando a sviluppare la Patch.

**Comment by tesivo** [comment]
Ottimo, allora ora troverai la traduzione.

Purtroppo ci sono dei problemi che insorgono quando ci sono frasi diverse a seconda del sesso del personaggio. Alcuni di questi bug possono essere scovati e risolti solo giocando.

Confermami che ti appare la traduzione anche di questi 3 dialoghi, resi con 2 (per il problema di qui sopra). Per l'altro problema invece non capisco dove sta il problema, dato che funziona tutto regolarmente, ma occorre premere barra spaziatrice. Per ora non ho idee a riguardo quindi premiamo la barra spaziatrice e continuiamo a giocare :D

**Comment by NarakuITA** [comment]
Sono In contatto con Wesp5, il creatore della patch. Vediamo se ci aiuterà.

**Comment by NarakuITA** [comment]
Allora; ha provato tutto, e lui, stranamente non gli si presenta il problema. Allora gli ho scritto se usa la barra spaziatrice, perché il problema si presenta se premi il tasto 1. Attendiamo la risposta.

**Comment by NarakuITA** [comment]
Questa è stata la sua risposta: _Pressing space during dialogue should do nothing. Maybe there is an issue with your config file? Also maybe this is connected to yo_ur Windows version?_
Sto cercando ancora di capire cosa intende esattamente.

**Comment by tesivo** [comment]
Domani vedo cosa potrebbe intendere, resta il fatto che a noi VTMB salta i dialoghi anche con la barra spaziatrice, e, a quanto pare, non dovrebbe xD

**Comment by NarakuITA** [comment]
Risposta:
_I meant that space is doing nothing during dialogues for me and if it does replace the number keys for you, it must be defined somewhere to do it. Maybe config.cfg or elsewhere? Also with Windows version I meant that you probably use an Italian version. Psycho-A always claimed that his Russian Windows couldn't display some characters that English and German Windows had no problems with..._

Magari è proprio la funzione della barra spaziatrice che fa in conflitto in quel punto. Visto che in teoria solo i numeri andrebbero usati. 
Tacca capire se è proprio questo. 
Mi è venuto in mente anche un'altra cosa. Dovremmo provare a usare il file in inglese e magari tradurre solamente quel pezzetto dove si blocca e vedere cosa succede.

**Comment by NarakuITA** [comment]
[jack_tutorial.zip](https://github.com/tesivo/VTMB_italian_translation_for_Unofficial_Patch/files/6480224/jack_tutorial.zip)
Allora, ho corretto il bug. Praticamente ci sono dei comandi che sono stati eliminati erroneamente: [sigh] e [distastefully]. A quanto pare le parole all'interno delle [] sono comandi, infatti non appaiono durante il dialogo. Inoltre tutte le {	} le ho riordinate, con gli spazi giusti ,tra l'una e l'altra e quelle che contendono i testi. Non mi dire il perché ma ora funziona tutto, puoi controllare dal 261 al 340 come ho ottimizzato e riordinato tutto in modo funzionante.

**Comment by NarakuITA** [comment]
Ora mi viene un dubbio atroce... e se questo problema si presente anche per altre Quest a noi ignote? Non vorrei che toccherebbe riordinare tutto e vedere se non sono stati levati, per errore altre comandi......

**Comment by NarakuITA** [comment]
No falso allarme, i sottotitoli nel video, mi sono apparti solo una volta ahahahaha Per il resto è tutto ok!

**Comment by tesivo** [comment]
Fantastico! Ora verifico il tutto e carico la tua correzione ;)

Ho fatto svariate prove, con solo il fix degli spazi, con solo il fix delle frasi con le [], usando l'hex editor...combinando i precedenti...ecc

La questione sembra essere molto più strana di quanto mi aspettassi:
-Gli spazi non creano problemi, che siano spazi o tab, ma, sembrerebbe che si debba fare spazio+tab oppure un solo spazio e bisogna evitare spazio+spazio, o almeno va evitato quando nel bel mezzo della frase (ho trovato anche un'altra frase con la medesima situazione, chissà se dava problemi boh):
	Mi riferisco alle righe 151(chissà se dava problemi) e 301(qui disabilitava il tasto 1 e l'audio e le animazioni di Jack)
-Le frasi tra [] è vero che non si vedono nei dialoghi, ma non sono dei comandi dato che, sia mettendole che non, funziona comunque tutto correttamente. Problabilmente erano delle linee guida per le animazioni e/o per il tono da usare nella realizzazione del doppiaggio. Chiaro è che potremmo anche non tradurle, ma possono fare comodo per, in fase di traduzione, o miglioramento della stessa, dare alla frase i giusti tono e traduzione.

Comunque, tornando a noi: prova ancora e confermami che ti funziona ancora tutto. (ho aggiunto le 4 frasi con [] che hai segnalato, corretto i 2 doppi spazi consecutivi, frase 151 e 301, mentre il resto l'ho lasciato stare)

**Comment by NarakuITA** [comment]
Si il bug non si presenta più. Ora è possibile proseguire il gioco. Tuttavia non si capisce perché alcuni dialoghi non si vede l'animazione in cui Jack parla.

**Comment by NarakuITA** [comment]
Wesp5  mi diceva che il problema dell'audio si potrebbe presentare se no è stato rinominato qualcosa nel file vcd. Perché il nome dell'oratore deve essere lo stesso del gioco.‎

**Comment by NarakuITA** [comment]
Wesp5: _I checked the lip file of the critical Jack line and it works fine for me too. Did you change anything in the Python script? Because I noticed you left out the icon in the quest log sign, but that wasn't the reason either. And you are right, everything between [ and ] is only a comment._

**Comment by NarakuITA** [comment]
Allora, ho capito quel è il problema. Ascolta bene:
Prendiamo per esempio la prima volta che Jack ti vede e ti parla. Ti dice: _Che spettacolo, amico! Ti hanno buttato qui proprio come un bambino nudo nella foresta._ ecc, ecc. Qui si rivolte a un Maschio e si sente l'audio di Jack parlare.
MA, MA, se si rivolge a una donna la frase cambia: _Che spettacolo, amica! Ti hanno buttato qui proprio come una bambina nuda nella foresta._ ecc, ecc. dunque se tu al posto della frase rivolta al personaggio femminile, ci metti la frase quella rivolta al personaggio maschile, tombola! Jack parla! Il gioco non è in grado di riconoscere la nostra grammatica, femminile e maschile, una grammatica più complessa di quella inglese.
Questo perché nel file, sound\character\dlg\main characters\jack_tutorial **line11_col_e.lip** è impostato solo per riconoscere la frase maschile; _Che spettacolo, amico! Ti hanno buttato qui proprio come un bambino nudo nella foresta._ ecc, ecc.
Chi sa se c'è il modo di aggirare questo problema.... Ne parlerò con Wesp5, ovviamente per lui andava tutto bene perché sicuramente  ha provato con un personaggio maschile e poi non essendo italiano non sa della nostra grammatica complessa rispetto all'inglese.

**Comment by tesivo** [comment]
Le altre problematiche di cui parlavi le hai riscontrate prima della serie di fix di stasera? Che in caso occorre anche lì indagare.

Ottima l'informazione sul file .vcd
Il file python non dovrebbe essere stato toccato, controllo per sicurezza ;)

**Comment by NarakuITA** [comment]
No tutto quello che ho scoperto L'ho scoperto sta sera con i nuovi file scaricati.

**Comment by tesivo** [comment]
Capito, spiegherebbe gli strani problemi che stiamo incontrando, o almeno parte di essi. Apriamo un nuovo issue per ogni problema, così manteniamo l'ordine. Qui chiudo visto che il problema di Jack che non si spostava pare risolto.

**Comment by NarakuITA** [comment]
Yes!
