### ISSUE TITLE
kb_act.lst Aggiornato

### ISSUE THREAD

**Issue by NarakuITA** [tesivo/VTMB_italian_translation_for_Unofficial_Patch#23]
Non sapendo dove scrivere, ho scritto qui. Scusate se non è la sessione giusta.
Vorrei contribuire riguardo il file "kb_act.lst" nella cartella "scripts" della Unofficial_Patch 10.7. Unica cosa non tradotto è "+strafe" non ho idea a cosa si riferisca esattamente.
File lavorato: [kb_act.zip](https://github.com/tesivo/VTMB_italian_translation_for_Unofficial_Patch/files/6447224/kb_act.zip)

Spero possa essere di aiuto.

"+forward"			"Avanti"
"+back"				"Indietro"
"+moveleft"			"Laterale sx"
"+moveright"			"Laterale dx"
"+strafe"			"Strafe modifier"
"+speed"             		"Cammina"
"autospeed"			"Alterna Cammina/Corri "
"automove"			"Spostamento automatico"
"+jump"				"Salta"
"+duck"				"Accucciati"
"+moveup"			"Scatto avanti"
"+movedown"			"Scatto indietro"
"+left"				"Girara a sinistra"
"+right"			"Girara a destra"
" "					" "
"+attack"			"Attacco Primario"
"+wpn_secondaryatk"		"Attacco secondario"
"+reload"			"Ricarica"
"holster"			"Fondina"
"lastinv"			"Ultima arma"
"dropitem"			"Lascia oggetto"
"slot2"				"Armi da mischia"
"slot3" 			"Armi a distanza"
"slot5"				"Armatura"
"slot6"				"Inventario"
"slot4"				"Armi da lancio"
"slot1"				"Discipline"
"vm_discipline"			"Usa disciplina"
//"vdiscipline_last"		"Usa Disciplina"
"vdiscipline_endall"		"Termina disciplina"
"toggleuiside"			"Attiva/Disattiva disciplina"
"invprev"			"Seleziona precedente"
"invnext"			"Seleziona successivo"
" "					" "
"+use"				"Usa"
"+feed"				"Nutriti"
"+questlog"			"Log delle Quest"
"+chareditor"			"Editor Personaggio"
"dlghist"			"Cronologia Dialoghi "
"dlgscrlup"			"Scorri su registro"
"dlgscrldn"			"Scorri giu' registro"
"pause"				"Pausa"
"snapshot"			"Stampa schermata"
"toggleconsole"			"Game Console"
"save quick"			"Salvataggio veloce"
"load quick"			"Caricamento veloce"
" "					" "
"showhotkeys"			"Menu hotkey"
"vhotkey #1"			"Hotkey 1"
"vhotkey #2"			"Hotkey 2"
"vhotkey #3"			"Hotkey 3"
"vhotkey #4"			"Hotkey 4"
"vhotkey #5"			"Hotkey 5"
"vhotkey #6"			"Hotkey 6"
"vhotkey #7"			"Hotkey 7"
"vhotkey #8"			"Hotkey 8"
"vhotkey #9"			"Hotkey 9"
"vhotkey #10"			"Hotkey 10"
" "					" "
"+mlook"			"Visuale mouse"
"togglecamera"			"1ma/3za persona"
"+camin"			"Camera: Ingrandire"
"+camout"			"Camera: Rimpicciolire"
"cam_rotateleft" 		"Camera: Gira a sinistra"
"cam_rotateright" 		"Camera: Gira a destra"
"cam_restore" 		"Camera: Ripristina"

**Comment by tesivo** [comment]
Grazie mille per il contributo, ho quasi integrato la tua modifica, ma prima mi servirebbe di sapere due cose:
- la riga "//"vdiscipline_last" "Usa Disciplina"" sicuro sia preceduta da //
- qual è la fonte per cui sai che vanno aggiunte 23 righe. 

Per strife ci devo pensare. Sembrerebbe un termine usato in inglese anche per noi.

**Comment by NarakuITA** [comment]
Si, sicurissimo. Ho solo tradotto il file. Ti passo il file originale in inglese, così puoi verificare se è tutto corretto.
[kb_act.zip](https://github.com/tesivo/VTMB_italian_translation_for_Unofficial_Patch/files/6448563/kb_act.zip)

**Comment by NarakuITA** [comment]
Si, il file è riferito alle 10.7. Direi di si, si finisce qui è poi quando te la senti passerai alla 10.9. In ogni caso. Per qualsiasi cosa, sempre lieto di aiutare.

**Comment by tesivo** [comment]
Posso confermare che il file funziona correttamente. Appena testato. A breve carico il tuo contributo ;)
