### ISSUE TITLE
Problema AUDIO nei dialoghi con personaggio femminile

### ISSUE THREAD

**Issue by NarakuITA** [tesivo/VTMB_italian_translation_for_Unofficial_Patch#24]
Allora, come abbiamo detto, abbiamo scoperto il problema delle terminologia, "maschile" e "femminile".
Sto scrivendo a Wesp5 per vedere se c'è il modo di aggirare tale problema: 
RIPORTO qui il messaggio dell'altro TOPC:

**Allora, ho capito quel è il problema. Ascolta bene:
Prendiamo per esempio la prima volta che Jack ti vede e ti parla. Ti dice: Che spettacolo, amico! Ti hanno buttato qui proprio come un bambino nudo nella foresta. ecc, ecc. Qui si rivolge a un Maschio e si sente l'audio di Jack parlare.
MA, MA, se si rivolge a una donna la frase cambia: Che spettacolo, amica! Ti hanno buttato qui proprio come una bambina nuda nella foresta. ecc, ecc. dunque se tu al posto della frase rivolta al personaggio femminile, ci metti la frase quella rivolta al personaggio maschile, tombola! Jack parla! Il gioco non è in grado di riconoscere la nostra grammatica, femminile e maschile, una grammatica più complessa di quella inglese.
Questo perché nel file, sound\character\dlg\main characters\jack_tutorial _line11_col_e.lip_ è impostato solo per riconoscere la frase maschile; Che spettacolo, amico! Ti hanno buttato qui proprio come un bambino nudo nella foresta. ecc, ecc.
Dunque tutte le volte che a un personaggio non si sente l'audio del suo parlato è perché la frase è rivolta a un personaggio femminile, e nella cartella sound, non ci sono file rivolti a quest'ultimi.
Chi sa se c'è il modo di aggirare questo problema.... Ne parlerò con Wesp5, ovviamente per lui andava tutto bene perché sicuramente ha provato con un personaggio maschile e poi non essendo italiano non sa della nostra grammatica complessa rispetto all'inglese.**

**Comment by tesivo** [comment]
Ho provato a creare un file line11_col_f.lip corrispondente alla versione femminile di line11_col_e.lip di jack_tutorial in sound, ma, peggiora solo le cose.

**Comment by NarakuITA** [comment]
Allora la tua scelta è giusta. Vedi la traduzione Francese: [https://github.com/FoolEcho/vtmb-up](url)
Vedi, su jack_tutorial.dlg, in questo caso la riga 1011. Ci sono le frasi sia per il maschile, sia per il femminile. 

Sempre il dialogo iniziale del Tutorial. In questo caso la frase femminile nostra è; 
- **Cosa? Oh, tesoro. E saresti anche tu una fottuta Malkavian? Wow, sei davvero nei guai.**
La loro: 
- **Quoi ? Oh bon sang, et en plus t'es du clan des Malkaviens ? Alors toi t'as la totale. . .**

Per riprodurre l'audio hanno due file nella solita cartella sound\character\dlg\main characters\jack_tutorial.
I file sono:

1. line1011_col_f.lip
2. line1011_col_f.vcd

Qui potrai notare molti file con il nome "line" e il numero uguale, ma che alla fine cambia l'esenzione e qualcos'altro. Potrai vedere come hanno aggirato il problema, puoi prendere spunto da loro. Io non sono a questi livelli, non sono in grado di usare un editor esadecimale. Almeno in questo caso, penso che ci vuole un editor, perché ho notato che tali frasi, non sono leggibili, e non appare il testo. Con Notepad, appare la scritta **NUL**.

**Comment by tesivo** [comment]
Giusto! Prendiamo spunto dai cugini francesi 🙂. Per i NULL non preoccuparti, se sostituisci UNICODE con CHAR poi puoi scrivere normalmente la stringa che desideri.

Comunque sia, faccio alcune prove e vedo di completare Jack tutorial e Mr. Ox. Dopodiché basterà mantenere questo stile e avremo tutto perfetto anche per i restanti dialoghi 😉

**Comment by tesivo** [comment]
intanto ho visto che non possiamo copiare i loro .vcd perchè non sono sempre le stesse frasi ad avere due traduzioni diverse a seconda del genere, vedi per esempio la riga 11 di jack_tutorial. Infine la loro versione di riferimento è la 10.6.

Comunque sia la strada giusta è questa quindi la seguiremo ;)

**Comment by NarakuITA** [comment]
Ho seguito il consiglio di Wesp5. Ho preso un vcd della 10.7  e cambiato solo i percorsi per i file audio e animazioni. Questi che ho fatto sono basati sulla nostra versione. 
[File vcd.zip](https://github.com/tesivo/VTMB_italian_translation_for_Unofficial_Patch/files/6485949/File.vcd.zip)
Crea un personaggio femminile e testa i miei file se anche a te funziona l'audio dei dialoghi. Quelli che devi sentire sono proprio le prime due frasi che Jack ti dice, poi arrivata alla scelta multipla, selezione l'opzione 2, dovrebbe essere quella: **Smettila e spiegami solo le basi.**
Controlla solo se l'audio corrisponde alla frase tradotta.

**Comment by tesivo** [comment]
A breve carico un po' di questi fix. Riguardo a quelli che hai fatto avrei però dei dubbi. Concordo sul cambiare il percorso del file audio, ovviamente, ma non delle animazioni, espressioni e trigger vari (fondamentalmente tali "channel" li lascerei vuoti). innanzi tutto perchè sono collegati ad un tempo(alcuni ricavabili, altri no, dato che non sappiamo sempre che animazione/espressione adoperare. Sostanzialmente potremmo applicare correttamente solo le pause, guardando i file .lip corrispondenti) e poi non credo che ad ogni audio ci siano sempre le stesse animazioni, pause ed espressioni. 

Ovviamente dovremmo fare una scelta, o mettiamo l'audio e solo quando siamo certi delle altre sezioni (gestures, expressions e speech triggers) anche gli altri canali, oppure aggiungiamo espressioni e animazioni a sentimento, ma non mi entusiasma questa ultima opzione :D

inoltre sistemerei sempre anche il tempo(del canale speech intendo), altrimenti potremmo perdere in sincronia tra labiale, suono e testo.

**Comment by NarakuITA** [comment]
Guarda secondo Wesp5, non c'è bisogno di modificare nulla, anzi anche i file francesi andavano bene. Basta cambiare solo i percorsi, il resto lasciare tutto com'è. Almeno lui mi ha detto così.
Effettivamente, noto che c'è sincronizzazione tra il labiale e l'audio. Forse il gioco si adatta l'audio, in modo automatico. Per questo Wesp5, mi ha consigliato di non toccare nulla, ma solo cambiare i percorsi. Cioè cambiare sotto "param" il percorso del file audio e il nome e  sotto "event gesture" sempre il nome.
Un esempio pratico nel file line11_col_f.vcd:
`param "character/dlg/main characters/jack_tutorial/line11_col_e.wav"
      param2 "70dB"
      fixedlength
    }
  }
  channel "Gestures"
  {
    event gesture "Smiling_Jack_line11_col_E"
    {
      time 0.000000 9.333333
      param "Smiling_Jack_line11_col_E"`

**Comment by tesivo** [comment]
Però ho notato che i francesi hanno alcune frasi diverse per il personaggio femminile che noi non abbiamo e noi ne abbiamo alcune che loro non hanno. 

Comunque entro sera carico jack tutorial con l'audio ok anche per il personaggio femminile e vediamo il risultato :D

Sisi, ha consigliato bene Wesp5 :) Però sono sicuro che ha dato per scontato che vada cambiato anche il nome dell'autore del dialogo e, questo più per la sincronizzazione dell'audio con il labiale, il tempo(cmq sia questa è una quisquilia :)). Poi per semplicità ha omesso che ci sarebbe tutta la questione animazioni, pause, tonalità della voce...Vuole aiutarci non confonderci :D

l'esempio che hai postato è ottimo e funzionante, ma avrà sicuramente il labiale desync e jack sorride. tutto ok se ci sta che sorrida, ma non può essere che sorrida sempre :D

**Comment by NarakuITA** [comment]
Umh, capisco, non saprei dirti, di preciso. So solo che mi ha anche mandato ora questo messaggio:
_BTW, the UP contains only vcd files that needed fixes. So either extract them yourself from the vpk archives or check the French ones which might be complete..._
Beh si forse che sorrida sempre, non sia il massimo, ma a quanto pare cmq ci consiglia di lavorare su quelli francesi, poi ovviamente dobbiamo sistemare le frasi e cambiare il nome dell'autore, come detto tu. 

Se per sta sera riesci a scovare tutti i dialoghi per il sesso femminile e sistemare il tutto con l'audio, bene! Sarò felice di testare.

**Comment by NarakuITA** [comment]
Umh, capisco, non saprei dirti, di preciso. So solo che mi ha anche mandato ora questo messaggio:
_BTW, the UP contains only vcd files that needed fixes. So either extract them yourself from the vpk archives or check the French ones which might be complete..._
Beh si forse che sorrida sempre, non sia il massimo, ma a quanto pare cmq ci consiglia di lavorare su quelli francesi, poi ovviamente dobbiamo sistemare le frasi e cambiare il nome dell'autore, come detto tu. 

Se per sta sera riesci a scovare tutti i dialoghi per il sesso femminile e sistemare il tutto con l'audio, bene! Sarò felice di testare.

**Comment by tesivo** [comment]
Ok, ho caricato il sonoro per il personaggio femminile che parla con jack nel tutorial. Non ho ancora avuto modo di testarli.

Riguardo all'ultima risposta di Wesp5: ha detto una cosa interessante. Giustamente la patch unofficial contiene solo e solamente i vcd di fix, quindi se si vuole trovare informazioni sugli altri vcd, se dovessero servirci, occorre trovare gli archivi vpk(li cerco e ti dico) oppure prendere spunto dal lavoro dei francesi (via che non consiglierei dato che non corrisponderebbe cmq con i vcd che ci servono).

**Comment by tesivo** [comment]
Tramite gli archivi vpk abbiamo tutte le informazioni sui file vcd che ci servono, con tanto di espressioni, pause, tonalità e animazioni :)

**Comment by NarakuITA** [comment]
Molto bene, così potrai sistemare accuratamente anche le espressioni, pause ecc. ecc.
Ho provato il tutorial più volte con più scelte, tutto funziona alla grande, audio, Jack che non blocca il passaggio, e i sottotitoli appaiono nel filmato.
