### ISSUE TITLE
TRADUZIONE ERRATA (FEMMINILE)

### ISSUE THREAD

**Issue by NarakuITA** [tesivo/VTMB_italian_translation_for_Unofficial_Patch#25]
![Vampire The Masquerade - Bloodlines Screenshot 2021 05 15 - 02 40 14 23](https://user-images.githubusercontent.com/38878793/118343173-9b5f5400-b527-11eb-8143-ebcae0cf9320.png)

Quando si gioca con un personaggio femminile, c'è un errore nella traduzione, jack ci si rivolge come se fossimo di sesso maschile.
Sostituire il termine "ragazzo" con "ragazza". 
Sempre nel file jack_tutorial.
Vedere immagine per la frase.

**Comment by tesivo** [comment]
Ok, correggo subito xD
