### ISSUE TITLE
Controllare la traduzione

### ISSUE THREAD

**Issue by NarakuITA** [tesivo/VTMB_italian_translation_for_Unofficial_Patch#31]
Ci sono degli errori di battitura. Nella descrizione Quest attive, controlla la "E", c'è ne è una di troppo e poi la parola "delle" nel dialogo.
![Vampire The Masquerade - Bloodlines Screenshot 2021 06 19 - 21 51 24 67](https://user-images.githubusercontent.com/38878793/122654881-8db47400-d14e-11eb-9155-ccd04d725a41.png)
![Vampire The Masquerade - Bloodlines Screenshot 2021 06 19 - 22 11 25 20](https://user-images.githubusercontent.com/38878793/122654883-9016ce00-d14e-11eb-878b-0806e790ee11.png)

**Comment by Kaiolith** [comment]
nella quest log non ci sono errori di battitura. è il personaggio sangue debole con cui hai parlato che si chiama E
